FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-noble AS build-env
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETARCH

WORKDIR /app

# Copy everything else and build
COPY . ./

RUN dotnet restore --ucr -a $TARGETARCH src/fhir-candle-minimal/fhir-candle-minimal.csproj
RUN dotnet publish --framework net9.0 -a $TARGETARCH src/fhir-candle-minimal/fhir-candle-minimal.csproj -c Release -o out --no-restore

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0-noble-chiseled
EXPOSE 5826
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "fhir-candle-minimal.dll"]
CMD ["-m", "1000"]
