using static FhirCandle.Utils.FhirReleases;

namespace fhir.candle.McpTools;

public class FhirTypeData
{
    public readonly record struct TypeDescriptionRec(
        FhirSequenceCodes MinFhirVersion,
        FhirSequenceCodes MaxFhirVersion,
        string Name,
        string Title,
        string Description,
        string? Comment
    )
    {
        public override string ToString() => $"{Name}: {Title} {Description} {Comment}";
    };

    static FhirTypeData()
    {
        TypeDescriptions = TypeDescriptionList.ToDictionary(r => r.Name);
    }

    public static readonly Dictionary<string, TypeDescriptionRec> TypeDescriptions;
    public static readonly List<TypeDescriptionRec> TypeDescriptionList = [
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Address", Title = "An address expressed using postal conventions (as opposed to GPS or other location definition formats)", Description = "Address Type: An address expressed using postal conventions (as opposed to GPS or other location definition formats).  This data type may be used to convey addresses for use in delivering mail as well as for visiting locations which might not be valid for mail delivery.  There are a variety of postal address formats defined around the world.\nThe ISO21090-codedString may be used to provide a coded representation of the contents of strings in an Address.", Comment = "Note: address is intended to describe postal addresses for administrative purposes, not to describe absolute geographical coordinates.  Postal addresses are often used as proxies for physical locations (also see the [Location](location.html#) resource)."},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Age", Title = "A duration of time during which an organism (or a process) has existed", Description = "Age Type: A duration of time during which an organism (or a process) has existed.", Comment = "The context of use may frequently define what kind of quantity this is and therefore what kind of units can be used. The context of use may also restrict the values for the comparator."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Annotation", Title = "Text node with attribution", Description = "Annotation Type: A  text note which also  contains information about who made the statement and when.", Comment = "For systems that do not have structured annotations, they can simply communicate a single annotation with no author or time.  This element may need to be included in narrative because of the potential for modifying information.  *Annotations SHOULD NOT* be used to communicate \"modifying\" information that could be computable. (This is a SHOULD because enforcing user behavior is nearly impossible)."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Attachment", Title = "Content in a format defined elsewhere", Description = "Attachment Type: For referring to data content defined in other formats.", Comment = "When providing a summary view (for example with Observation.value[x]) Attachment should be represented with a brief display text such as \"Signed Procedure Consent\"."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "BackboneElement", Title = "Base for elements defined inside a resource", Description = "BackboneElement Type: Base definition for all elements that are defined inside a resource - but not those in a data type.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R5, MaxFhirVersion = FhirSequenceCodes.R5, Name = "BackboneType", Title = "Base for datatypes that can carry modifier extensions", Description = "BackboneType Type: Base definition for the few data types that are allowed to carry modifier extensions.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R5, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Base", Title = "Base for all types and resources", Description = "Base Type: Base definition for all types defined in FHIR type system.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "CodeableConcept", Title = "Concept - reference to a terminology or just  text", Description = "CodeableConcept Type: A concept that may be defined by a formal reference to a terminology or ontology or may be provided by text.", Comment = "Not all terminology uses fit this general pattern. In some cases, models should not use CodeableConcept and use Coding directly and provide their own structure for managing text, codings, translations and the relationship between elements and pre- and post-coordination."},
        new() { MinFhirVersion = FhirSequenceCodes.R4B, MaxFhirVersion = FhirSequenceCodes.R5, Name = "CodeableReference", Title = "Reference to a resource or a concept", Description = "CodeableReference Type: A reference to a resource (by instance), or instead, a reference to a concept defined in a terminology or ontology (by class).", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Coding", Title = "A reference to a code defined by a terminology system", Description = "Coding Type: A reference to a code defined by a terminology system.", Comment = "Codes may be defined very casually in enumerations or code lists, up to very formal definitions such as SNOMED CT - see the HL7 v3 Core Principles for more information."},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "ContactDetail", Title = "Contact information", Description = "ContactDetail Type: Specifies contact information for a person or organization.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "ContactPoint", Title = "Details of a Technology mediated contact point (phone, fax, email, etc.)", Description = "ContactPoint Type: Details for all kinds of technology mediated contact points for a person or organization, including telephone, email, etc.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Contributor", Title = "Contributor information", Description = "Contributor Type: A contributor to the content of a knowledge asset, including authors, editors, reviewers, and endorsers.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Count", Title = "A measured or measurable amount", Description = "Count Type: A measured amount (or an amount that can potentially be measured). Note that measured amounts include amounts that are not precisely quantified, including amounts involving arbitrary units and floating currencies.", Comment = "The context of use may frequently define what kind of quantity this is and therefore what kind of units can be used. The context of use may also restrict the values for the comparator."},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "DataRequirement", Title = "Describes a required data item", Description = "DataRequirement Type: Describes a required data item for evaluation in terms of the type of data, and optional code or date-based filters of the data.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R4B, MaxFhirVersion = FhirSequenceCodes.R5, Name = "DataType", Title = "Reuseable Types", Description = "DataType Type: The base class for all re-useable types defined as part of the FHIR Specification.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Distance", Title = "A length - a value with a unit that is a physical distance", Description = "Distance Type: A length - a value with a unit that is a physical distance.", Comment = "The context of use may frequently define what kind of quantity this is and therefore what kind of units can be used. The context of use may also restrict the values for the comparator."},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Dosage", Title = "How the medication is/was taken or should be taken", Description = "Dosage Type: Indicates how the medication is/was taken or should be taken by the patient.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Duration", Title = "A length of time", Description = "Duration Type: A length of time.", Comment = "The context of use may frequently define what kind of quantity this is and therefore what kind of units can be used. The context of use may also restrict the values for the comparator."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Element", Title = "Base for all elements", Description = "Element Type: Base definition for all elements in a resource.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "ElementDefinition", Title = "Definition of an element in a resource or extension", Description = "ElementDefinition Type: Captures constraints on each element within the resource, profile, or extension.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Expression", Title = "An expression that can be used to generate a value", Description = "Expression Type: A expression that is evaluated in a specified context and returns a value. The context of use of the expression must specify the context in which the expression is evaluated, and how the result of the expression is used.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R5, MaxFhirVersion = FhirSequenceCodes.R5, Name = "ExtendedContactDetail", Title = "Contact information", Description = "ExtendedContactDetail Type: Specifies contact information for a specific purpose over a period of time, might be handled/monitored by a specific named person or organization.", Comment = "This datatype may be sparsely populated, i.e. only contain a purpose and phone number or address, but other cases could be completed filled out."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Extension", Title = "Optional Extensions Element", Description = "Extension Type: Optional Extension Element - found in all resources.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "HumanName", Title = "Name of a human or other living entity - parts and usage", Description = "HumanName Type: A name, normally of a human, that can be used for other living entities (e.g. animals but not organizations) that have been assigned names by a human and may need the use of name parts or the need for usage information.", Comment = "Names may be changed, or repudiated, or people may have different names in different contexts. Names may be divided into parts of different type that have variable significance depending on context, though the division into parts does not always matter. With personal names, the different parts might or might not be imbued with some implicit meaning; various cultures associate different importance with the name parts and the degree to which systems must care about name parts around the world varies widely."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Identifier", Title = "An identifier intended for computation", Description = "Identifier Type: An identifier - identifies some entity uniquely and unambiguously. Typically this is used for business identifiers.", Comment = "The rules of the identifier.type  determine if a check digit is part of the ID value or sent separately, such as through the checkDigit extension."},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R5, Name = "MarketingStatus", Title = "The marketing status describes the date when a medicinal product is actually put on the market or the date as of which it is no longer available", Description = "MarketingStatus Type: The marketing status describes the date when a medicinal product is actually put on the market or the date as of which it is no longer available.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Meta", Title = "Metadata about a resource", Description = "Meta Type: The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R5, MaxFhirVersion = FhirSequenceCodes.R5, Name = "MonetaryComponent", Title = "Availability data for an {item}", Description = "MonetaryComponent Type: Availability data for an {item}.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Money", Title = "An amount of economic utility in some recognized currency", Description = "Money Type: An amount of economic utility in some recognized currency.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Narrative", Title = "Human-readable summary of the resource (essential clinical and business information)", Description = "Narrative Type: A human-readable summary of the resource conveying the essential clinical and business information for the resource.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "ParameterDefinition", Title = "Definition of a parameter to a module", Description = "ParameterDefinition Type: The parameters to the module. This collection specifies both the input and output parameters. Input parameters are provided by the caller as part of the $evaluate operation. Output parameters are included in the GuidanceResponse.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Period", Title = "Time range defined by start and end date/time", Description = "Period Type: A time period defined by a start and end date and optionally time.", Comment = "A Period specifies a range of time; the context of use will specify whether the entire range applies (e.g. \"the patient was an inpatient of the hospital for this time range\") or one value from the range applies (e.g. \"give to the patient between these two times\").\n\nPeriod is not used for a duration (a measure of elapsed time). See [Duration](datatypes.html#Duration)."},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R4B, Name = "Population", Title = "A definition of a set of people that apply to some clinically related context, for example people contraindicated for a certain medication", Description = "Base StructureDefinition for Population Type: A populatioof people with some set of grouping criteria.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R5, MaxFhirVersion = FhirSequenceCodes.R5, Name = "PrimitiveType", Title = "Parent type for DataTypes with a simple value", Description = "PrimitiveType Type: The base type for all re-useable types defined that have a simple property.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R4B, Name = "ProdCharacteristic", Title = "The marketing status describes the date when a medicinal product is actually put on the market or the date as of which it is no longer available", Description = "Base StructureDefinition for ProdCharacteristic Type: The marketing status describes the date when a medicinal product is actually put on the market or the date as of which it is no longer available.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R5, Name = "ProductShelfLife", Title = "The shelf-life and storage information for a medicinal product item or container can be described using this class", Description = "ProductShelfLife Type: The shelf-life and storage information for a medicinal product item or container can be described using this class.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Quantity", Title = "A measured or measurable amount", Description = "Quantity Type: A measured amount (or an amount that can potentially be measured). Note that measured amounts include amounts that are not precisely quantified, including amounts involving arbitrary units and floating currencies.", Comment = "The context of use may frequently define what kind of quantity this is and therefore what kind of units can be used. The context of use may also restrict the values for the comparator."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Range", Title = "Set of values bounded by low and high", Description = "Range Type: A set of ordered Quantities defined by a low and high limit.", Comment = "The stated low and high value are assumed to have arbitrarily high precision when it comes to determining which values are in the range. I.e. 1.99 is not in the range 2 -> 3."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Ratio", Title = "A ratio of two Quantity values - a numerator and a denominator", Description = "Ratio Type: A relationship of two Quantity values - expressed as a numerator and a denominator.", Comment = "The Ratio datatype should only be used to express a relationship of two numbers if the relationship cannot be suitably expressed using a Quantity and a common unit.  Where the denominator value is known to be fixed to \"1\", Quantity should be used instead of Ratio."},
        new() { MinFhirVersion = FhirSequenceCodes.R4B, MaxFhirVersion = FhirSequenceCodes.R5, Name = "RatioRange", Title = "Range of ratio values", Description = "RatioRange Type: A range of ratios expressed as a low and high numerator and a denominator.", Comment = "The stated low and high value are assumed to have arbitrarily high precision when it comes to determining which values are in the range. I.e. 1.99 is not in the range 2 -> 3."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Reference", Title = "A reference from one resource to another", Description = "Reference Type: A reference from one resource to another.", Comment = "References SHALL be a reference to an actual FHIR resource, and SHALL be resolvable (allowing for access control, temporary unavailability, etc.). Resolution can be either by retrieval from the URL, or, where applicable by resource type, by treating an absolute reference as a canonical URL and looking it up in a local registry/repository."},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "RelatedArtifact", Title = "Related artifacts for a knowledge resource", Description = "RelatedArtifact Type: Related artifacts such as additional documentation, justification, or bibliographic references.", Comment = "Each related artifact is either an attachment, or a reference to another knowledge resource, but not both."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "SampledData", Title = "A series of measurements taken by a device", Description = "SampledData Type: A series of measurements taken by a device, with upper and lower limits. There may be more than one dimension in the data.", Comment = "The data is not interpretable without at least origin, period, and dimensions, but these are optional to allow a separation between the template of measurement and the actual measurement, such as between DeviceCapabilities and DeviceLog.  When providing a summary view (for example with Observation.value[x]) SampledData should be represented with a brief display text such as \"Sampled Data\"."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Signature", Title = "A Signature - XML DigSig, JWS, Graphical image of signature, etc.", Description = "Signature Type: A signature along with supporting context. The signature may be a digital signature that is cryptographic in nature, or some other signature acceptable to the domain. This other signature may be as simple as a graphical image representing a hand-written signature, or a signature ceremony Different signature approaches have different utilities.", Comment = "The elements of the Signature Resource are for ease of access of these elements. For digital signatures (Xml DigSig, JWS), the non-repudiation proof comes from the Signature  validation, which includes validation of the referenced objects (e.g. Resources) (a.k.a., Content) in the XML-Signature Detached form."},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R4, Name = "SubstanceAmount", Title = "Chemical substances are a single substance type whose primary defining element is the molecular structure. Chemical substances shall be defined on the basis of their complete covalent molecular structure; the presence of a salt (counter-ion) and/or solvates (water, alcohols) is also captured. Purity, grade, physical form or particle size are not taken into account in the definition of a chemical substance or in the assignment of a Substance ID", Description = "Base StructureDefinition for SubstanceAmount Type: Chemical substances are a single substance type whose primary defining element is the molecular structure. Chemical substances shall be defined on the basis of their complete covalent molecular structure; the presence of a salt (counter-ion) and/or solvates (water, alcohols) is also captured. Purity, grade, physical form or particle size are not taken into account in the definition of a chemical substance or in the assignment of a Substance ID.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "Timing", Title = "A timing schedule that specifies an event that may occur multiple times", Description = "Timing Type: Specifies an event that may occur multiple times. Timing schedules are used to record when things are planned, expected or requested to occur. The most common usage is in dosage instructions for medications. They are also used when planning care of various kinds, and may be used for reporting the schedule to which past regular activities were carried out.", Comment = "Describes the occurrence of an event that may occur multiple times. Timing schedules are used for specifying when events are expected or requested to occur, and may also be used to represent the summary of a past or ongoing event.  For simplicity, the definitions of Timing components are expressed as 'future' events, but such components can also be used to describe historic or ongoing events.\n\nA Timing schedule can be a list of events and/or criteria for when the event happens, which can be expressed in a structured form and/or as a code. When both event and a repeating specification are provided, the list of events should be understood as an interpretation of the information in the repeat structure."},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "TriggerDefinition", Title = "Defines an expected trigger for a module", Description = "TriggerDefinition Type: A description of a triggering event. Triggering events can be named events, data events, or periodic, as determined by the type element.", Comment = "If an event is a named-event, it means the event is completely pre-coordinated, and no other information can be specified for the event. If the event is one of the data- events, the data and condition elements specify the triggering criteria. The data element specifies the structured component, and the condition element provides additional optional refinement of that structured component. If the event is periodic, the timing element defines when the event is triggered. For both data- and periodic events, a name can be provided as a shorthand for the formal semantics provided by the other elements."},
        new() { MinFhirVersion = FhirSequenceCodes.STU3, MaxFhirVersion = FhirSequenceCodes.R5, Name = "UsageContext", Title = "Describes the context of use for a conformance or knowledge resource", Description = "UsageContext Type: Specifies clinical/business/etc. metadata that can be used to retrieve, index and/or categorize an artifact. This metadata can either be specific to the applicable population (e.g., age category, DRG) or the specific context of care (e.g., venue, care setting, provider of care).", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R5, MaxFhirVersion = FhirSequenceCodes.R5, Name = "VirtualServiceDetail", Title = "Virtual Service Contact Details", Description = "VirtualServiceDetail Type: Virtual Service Contact Details.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "base64Binary", Title = "Primitive Type base64Binary", Description = "base64Binary Type: A stream of bytes", Comment = "A stream of bytes, base64 encoded"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "boolean", Title = "Primitive Type boolean", Description = "boolean Type: Value of \"true\" or \"false\"", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R5, Name = "canonical", Title = "Primitive Type canonical", Description = "canonical type: A URI that is a reference to a canonical URL on a FHIR resource", Comment = "see [Canonical References](references.html#canonical)"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "code", Title = "Primitive Type code", Description = "code type: A string which has at least one character and no leading or trailing whitespace and where there is no whitespace other than single spaces in the contents", Comment = "Note that FHIR strings SHALL NOT exceed 1,048,576 (1024*1024) characters in size"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "date", Title = "Primitive Type date", Description = "date Type: A date or partial date (e.g. just year or year + month). There is no UTC offset. The format is a union of the schema types gYear, gYearMonth and date.  Dates SHALL be valid dates.", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "dateTime", Title = "Primitive Type dateTime", Description = "dateTime Type: A date, date-time or partial date (e.g. just year or year + month).  If hours and minutes are specified, a UTC offset SHALL be populated. The format is a union of the schema types gYear, gYearMonth, date and dateTime. Seconds must be provided due to schema type constraints but may be zero-filled and may be ignored.                 Dates SHALL be valid dates.", Comment = "UTC offset is allowed for dates and partial dates"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "decimal", Title = "Primitive Type decimal", Description = "decimal Type: A rational number with implicit precision", Comment = "Do not use an IEEE type floating point type, instead use something that works like a true decimal, with inbuilt precision (e.g. Java BigInteger)"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "id", Title = "Primitive Type id", Description = "id type: Any combination of letters, numerals, \"-\" and \".\", with a length limit of 64 characters.  (This might be an integer, an unprefixed OID, UUID or any other identifier pattern that meets these constraints.)  Ids are case-insensitive.", Comment = "RFC 4122"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "instant", Title = "Primitive Type instant", Description = "instant Type: An instant in time - known at least to the second", Comment = "Note: This is intended for where precisely observed times are required, typically system logs etc., and not human-reported times - for them, see date and dateTime (which can be as precise as instant, but is not required to be) below. UTC offset is always required"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "integer", Title = "Primitive Type integer", Description = "integer Type: A whole number", Comment = "32 bit number; for values larger than this, use decimal"},
        new() { MinFhirVersion = FhirSequenceCodes.R5, MaxFhirVersion = FhirSequenceCodes.R5, Name = "integer64", Title = "Primitive Type integer64", Description = "integer64 Type: A very large whole number", Comment = "Typically this is used for record counters (e.g. database keys)"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "markdown", Title = "Primitive Type markdown", Description = "markdown type: A string that may contain Github Flavored Markdown syntax for optional processing by a mark down presentation engine", Comment = "Systems are not required to have markdown support, so the text should be readable without markdown processing. The markdown syntax is GFM - see https://github.github.com/gfm/"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "oid", Title = "Primitive Type oid", Description = "oid type: An OID represented as a URI", Comment = "RFC 3001. See also ISO/IEC 8824:1990 €"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "positiveInt", Title = "Primitive Type positiveInt", Description = "positiveInt type: An integer with a value that is positive (e.g. >0)", Comment = "32 bit number; for values larger than this, use decimal"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "string", Title = "Primitive Type string", Description = "string Type: A sequence of Unicode characters", Comment = "Note that FHIR strings SHALL NOT exceed 1,048,576 (1024*1024) characters in size"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "time", Title = "Primitive Type time", Description = "time Type: A time during the day, with no date specified", Comment = null},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "unsignedInt", Title = "Primitive Type unsignedInt", Description = "unsignedInt type: An integer with a value that is not negative (e.g. >= 0)", Comment = "32 bit number; for values larger than this, use decimal"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "uri", Title = "Primitive Type uri", Description = "uri Type: String of characters used to identify a name or a resource", Comment = "see http://en.wikipedia.org/wiki/Uniform_resource_identifier"},
        new() { MinFhirVersion = FhirSequenceCodes.R4, MaxFhirVersion = FhirSequenceCodes.R5, Name = "url", Title = "Primitive Type url", Description = "url type: A URI that is a literal reference", Comment = "see http://en.wikipedia.org/wiki/Uniform_resource_identifier"},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "uuid", Title = "Primitive Type uuid", Description = "uuid type: A UUID, represented as a URI", Comment = "See The Open Group, CDE 1.1 Remote Procedure Call specification, Appendix A."},
        new() { MinFhirVersion = FhirSequenceCodes.DSTU2, MaxFhirVersion = FhirSequenceCodes.R5, Name = "xhtml", Title = "Primitive Type xhtml", Description = "xhtml Type definition", Comment = null},
    ];
}
