name: Deploy to *.argo.run
# Basics from https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/github-actions
on:
  push:
    branches:
    - main-disabled

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # - uses: azure/docker-login@v1
    #   with:
    #     login-server: ${{ secrets.ARGO_CONTAINER_REGISTRY }}
    #     username: ${{ fromJSON(secrets.ARGO_AZ_CREDENTIALS_23).clientId }}
    #     password: ${{ fromJSON(secrets.ARGO_AZ_CREDENTIALS_23).clientSecret }}
    # - uses: azure/aks-set-context@v1
    #   with:
    #     creds: '${{ secrets.ARGO_AZ_CREDENTIALS_23 }}'
    #     cluster-name: ${{ secrets.ARGO_CLUSTER_NAME_23 }}
    #     resource-group: ${{ secrets.ARGO_RESOURCE_GROUP }}

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ fromJSON(secrets.ARGO_AZ_CREDENTIALS_23).clientId }}
        tenant-id: ${{ fromJSON(secrets.ARGO_AZ_CREDENTIALS_23).tenantId }}
        subscription-id: ${{ fromJSON(secrets.ARGO_AZ_CREDENTIALS_23).subscriptionId }}
    - name: Login to ACR via OIDC
      run: az acr login --name ${{ secrets.ARGO_CONTAINER_REGISTRY }}

    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
         kubelogin-version: 'v0.0.24'
    - uses: azure/aks-set-context@v3
      with:
        admin: false
        use-kubelogin: true
        cluster-name: ${{ secrets.ARGO_CLUSTER_NAME_23 }}
        resource-group: ${{ secrets.ARGO_RESOURCE_GROUP }}

    - name: Build and rollout to CI
      run: |
        docker build . \
          -t ${{ secrets.ARGO_CONTAINER_REGISTRY }}/subscriptions/fhir-candle:$GITHUB_SHA \
          -t ${{ secrets.ARGO_CONTAINER_REGISTRY }}/subscriptions/fhir-candle:latest
        docker push ${{ secrets.ARGO_CONTAINER_REGISTRY }}/subscriptions/fhir-candle
        kubectl -n subscriptions-ri rollout restart deployment
