name: Publish dotnet tool
# Basics from https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/github-actions
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Tests']
    types: [completed]
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            9.0
            8.0

    - name: Build and Publish
      run: |
        dotnet restore src/fhir-candle/fhir-candle.csproj
        dotnet pack -c Release ./src/fhir-candle/fhir-candle.csproj
        mv ./src/fhir-candle/bin/Release/net8.0/publish/wwwroot ./src/fhir-candle/bin/Release/net8.0/publish/staticwebassets
        mv ./src/fhir-candle/bin/Release/net9.0/publish/wwwroot ./src/fhir-candle/bin/Release/net9.0/publish/staticwebassets
        7z a ./nupkg/*.nupkg ./src/fhir-candle/bin/Release/net8.0/publish/staticwebassets/
        7z a ./nupkg/*.nupkg ./src/fhir-candle/bin/Release/net9.0/publish/staticwebassets/
        dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GINOC_NUGET }} --source https://api.nuget.org/v3/index.json
